name: muza
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0' # Updated the SDK version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.5.0
  audio_service: ^0.18.12
  just_audio: ^0.9.35
  audioplayers: ^5.1.0
  permission_handler: ^11.0.0
  assets_audio_player: ^3.1.1
  path_provider: ^2.1.1
  on_audio_query: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Zen Dots
      fonts:
        - asset: assets/font/ZenDots-Regular.ttf
  #         - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
